#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Abdu Elturki 
url: 'http://abdu.uk'
#baseurl: 'abduelturki.github.io' #change it according to your repository name
description: Abdu Elturki 
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: 4B6A78 

# Tracker
analytics:



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: localhost
safe: false
